// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fvodijhgpefmxtgpkfdf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ2b2RpamhncGVmbXh0Z3BrZmRmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1NjIwMDksImV4cCI6MjA2NjEzODAwOX0.15tLbTkO827uWBmjvw6XWV4FPUUAEZ51JXytNuK7uvM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);